FROM golang:1.25-bookworm

RUN apt-get update && apt-get install -y zsh \
    curl \
    git

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

CMD ["tail", "-f", "/dev/null"]