services:

  api:
    volumes:
      - .:/app  # Mount current directory for live code changes
    ports:
      - "${PORT-8080}:${PORT-8080}"
    command: sleep infinity

  db:
    restart: unless-stopped
