FROM golang:1.24.2

RUN apt-get update && apt-get install -y zsh \
    curl \
    git

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/jstemmer/go-junit-report@latest
RUN go install github.com/afunix/gocov/gocov@latest
RUN go install github.com/vinils/gocov-xml@latest


CMD ["tail", "-f", "/dev/null"]