services:
  api:
    image: api
    build: .

  db:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER-postgres} -d ${DB_DB-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: